#pragma once

#define ENABLE_ANTI_ALIASING

#define ENABLE_MULTITHREAD

#define ENABLE_BVH

#define ENABLE_REFRACTION

#define ENABLE_REFLECTION

#define ENABLE_GLOSSY_REFLECTION

#define ENABLE_GLOSSY_REFRACTION

#define ENABLE_SOFTSHADOW

// #define ENABLE_DEPTH_OF_FIELD